// <auto-generated />
// Generated from crates/wasm-echarts/pkg/wasm_echarts.js — re-run tools/GenWbgImports after wasm-pack.
#nullable enable
using Wasmtime;

namespace WasmCharts.Runtime;

internal static partial class WbgImports
{
    private static readonly Dictionary<string, WbgKind> Kinds = new()
    {
        ["__wbg___wbindgen_boolean_get_edaed31a367ce1bd"] = WbgKind.BooleanGet,
        ["__wbg___wbindgen_copy_to_typed_array_c5728021fabd0236"] = WbgKind.CopyToTypedArray,
        ["__wbg___wbindgen_debug_string_8a447059637473e2"] = WbgKind.DebugString,
        ["__wbg___wbindgen_is_function_acc5528be2b923f2"] = WbgKind.IsFunction,
        ["__wbg___wbindgen_is_null_6d937fbfb6478470"] = WbgKind.IsNull,
        ["__wbg___wbindgen_is_object_0beba4a1980d3eea"] = WbgKind.IsObject,
        ["__wbg___wbindgen_is_string_1fca8072260dd261"] = WbgKind.IsString,
        ["__wbg___wbindgen_is_undefined_721f8decd50c87a3"] = WbgKind.IsUndefined,
        ["__wbg___wbindgen_jsval_eq_4e8c38722cb8ff51"] = WbgKind.JsvalEq,
        ["__wbg___wbindgen_number_get_1cc01dd708740256"] = WbgKind.NumberGet,
        ["__wbg___wbindgen_string_get_71bb4348194e31f0"] = WbgKind.StringGet,
        ["__wbg___wbindgen_throw_ea4887a5f8f9a9db"] = WbgKind.Throw,
        ["__wbg__wbg_cb_unref_33c39e13d73b25f6"] = WbgKind.ClosureUnref,
        ["__wbg_addEventListener_ea90bc131475777e"] = WbgKind.AddEventListener,
        ["__wbg_call_0e855b388e315e17"] = WbgKind.Call3,
        ["__wbg_call_5575218572ead796"] = WbgKind.Call2,
        ["__wbg_call_8e98ed2f3c86c4b5"] = WbgKind.Call1,
        ["__wbg_clientX_7d645a0b265349f0"] = WbgKind.ClientX,
        ["__wbg_clientY_558c61970f6b424a"] = WbgKind.ClientY,
        ["__wbg_createElement_9e23ac95e40e302c"] = WbgKind.CreateElement,
        ["__wbg_customseriesapi_new"] = WbgKind.WrapCustomSeriesApi,
        ["__wbg_data_411cafdcea483b74"] = WbgKind.ImageDataBytes,
        ["__wbg_document_2634180a4c694068"] = WbgKind.Document,
        ["__wbg_drawImage_baead0925fc14e5f"] = WbgKind.DrawImage,
        ["__wbg_element_new"] = WbgKind.WrapElement,
        ["__wbg_error_6fe2f1675730f2bd"] = WbgKind.ConsoleError2,
        ["__wbg_error_a6fa202b58aa1cd3"] = WbgKind.ConsoleErrorString,
        ["__wbg_from_50138b2ca136f50c"] = WbgKind.ArrayFrom,
        ["__wbg_getBoundingClientRect_bf4a017da5494fc9"] = WbgKind.GetBoundingClientRect,
        ["__wbg_getContext_486aab500e1c34c9"] = WbgKind.GetContext,
        ["__wbg_getImageData_bcdd3d54c5e0f471"] = WbgKind.GetImageData,
        ["__wbg_get_197a3fe98f169e38"] = WbgKind.ArrayGet,
        ["__wbg_get_dddb90ff5d27a080"] = WbgKind.ReflectGet,
        ["__wbg_get_unchecked_54a4374c38e08460"] = WbgKind.ArrayGet,
        ["__wbg_height_a04613570d793df2"] = WbgKind.HeightI32,
        ["__wbg_height_cd732bbdc7b66e49"] = WbgKind.HeightF64,
        ["__wbg_instanceof_Array_49598245ad12c736"] = WbgKind.InstanceofArray,
        ["__wbg_instanceof_CanvasRenderingContext2d_d0cab9e931424c52"] = WbgKind.InstanceofCanvas2d,
        ["__wbg_instanceof_Element_7cd17aeb1babd05e"] = WbgKind.InstanceofElement,
        ["__wbg_instanceof_Function_b095a979bd8cd39d"] = WbgKind.InstanceofFunction,
        ["__wbg_instanceof_HtmlCanvasElement_8ce29a370a2b10a4"] = WbgKind.InstanceofCanvas,
        ["__wbg_instanceof_HtmlImageElement_83e43a035d4d5033"] = WbgKind.InstanceofImage,
        ["__wbg_instanceof_Object_60be3eaa7a661141"] = WbgKind.InstanceofObject,
        ["__wbg_instanceof_Uint8Array_f080092dc70f5d58"] = WbgKind.InstanceofUint8Array,
        ["__wbg_instanceof_Window_0d356b88a2f77c42"] = WbgKind.InstanceofWindow,
        ["__wbg_isArray_145a34fd0a38d37b"] = WbgKind.IsArray,
        ["__wbg_keys_e2132f5645c137bf"] = WbgKind.ObjectKeys,
        ["__wbg_left_fd8e5732a10e0137"] = WbgKind.DomLeft,
        ["__wbg_length_589238bdcf171f0e"] = WbgKind.Length,
        ["__wbg_length_c6054974c0a6cdb9"] = WbgKind.Length,
        ["__wbg_naturalHeight_7cbdc2f637f6914f"] = WbgKind.NaturalHeight,
        ["__wbg_naturalWidth_5c95710d6c0ff97a"] = WbgKind.NaturalWidth,
        ["__wbg_new_227d7c05414eb861"] = WbgKind.NewError,
        ["__wbg_new_2e117a478906f062"] = WbgKind.NewObject,
        ["__wbg_new_36e147a8ced3c6e0"] = WbgKind.NewArray,
        ["__wbg_new_from_slice_543b875b27789a8f"] = WbgKind.NewUint8ArrayFromSlice,
        ["__wbg_new_with_length_bb4d6b8628a4f23a"] = WbgKind.NewArrayWithLength,
        ["__wbg_new_with_u8_clamped_array_and_sh_adb3f647b0414eb2"] = WbgKind.NewImageData,
        ["__wbg_now_d2e0afbad4edbe82"] = WbgKind.DateNow,
        ["__wbg_ownKeys_9c0857bab4917919"] = WbgKind.OwnKeys,
        ["__wbg_pointerId_2c4027fd33473f83"] = WbgKind.PointerId,
        ["__wbg_prototypesetcall_d721637c7ca66eb8"] = WbgKind.TypedArraySetFromWasm,
        ["__wbg_push_f724b5db8acf89d2"] = WbgKind.ArrayPush,
        ["__wbg_putImageData_d36ffa8305aea239"] = WbgKind.PutImageData,
        ["__wbg_querySelector_45b96634e7f85460"] = WbgKind.QuerySelector,
        ["__wbg_releasePointerCapture_746a323c70b5cff4"] = WbgKind.ReleasePointerCapture,
        ["__wbg_removeEventListener_c6782a9c30557d31"] = WbgKind.RemoveEventListener,
        ["__wbg_setPointerCapture_87f6b55ceca474a9"] = WbgKind.SetPointerCapture,
        ["__wbg_setProperty_da5e4438a912e787"] = WbgKind.SetProperty,
        ["__wbg_set_4564f7dc44fcb0c9"] = WbgKind.ReflectSet,
        ["__wbg_set_dc601f4a69da0bc2"] = WbgKind.ArraySet,
        ["__wbg_set_height_ad5056ea051acd78"] = WbgKind.SetHeight,
        ["__wbg_set_width_031bdecd763c5855"] = WbgKind.SetWidth,
        ["__wbg_stack_3b0d974bbf31e44f"] = WbgKind.ErrorStack,
        ["__wbg_static_accessor_GLOBAL_THIS_2fee5048bcca5938"] = WbgKind.GlobalThis,
        ["__wbg_static_accessor_GLOBAL_ce44e66a4935da8c"] = WbgKind.Global,
        ["__wbg_static_accessor_SELF_44f6e0cb5e67cdad"] = WbgKind.Self,
        ["__wbg_static_accessor_WINDOW_168f178805d978fe"] = WbgKind.Window,
        ["__wbg_style_f00fbf31e0a68f0e"] = WbgKind.Style,
        ["__wbg_top_b0669fa399851b2e"] = WbgKind.DomTop,
        ["__wbg_warn_cd671287bc02594a"] = WbgKind.ConsoleWarn,
        ["__wbg_width_a86bcd32bd998060"] = WbgKind.WidthF64,
        ["__wbg_width_c8740d5bdf596189"] = WbgKind.WidthI32,
        ["__wbindgen_cast_0000000000000001"] = WbgKind.CastClosure,
        ["__wbindgen_cast_0000000000000002"] = WbgKind.CastF64,
        ["__wbindgen_cast_0000000000000003"] = WbgKind.CastString,
        ["__wbindgen_init_externref_table"] = WbgKind.InitExternrefTable,
    };

    public static void Define(Linker linker, Module module, WbgHost host)
    {
        foreach (var import in module.Imports)
        {
            if (import is not FunctionImport fn)
            {
                continue;
            }

            var name = import.Name;
            var kind = Kinds.GetValueOrDefault(name, WbgKind.NotImplemented);
            linker.DefineFunction(
                import.ModuleName,
                name,
                (Caller caller, ReadOnlySpan<ValueBox> args, Span<ValueBox> results) =>
                    host.Invoke(kind, name, caller, args, results),
                fn.Parameters,
                fn.Results);
        }
    }
}
